feat : 위도 경도 찾는 기능 및 찾은 위도경도로 전방 미터당 마트 정보 조회 기능 구현 + yml 암호화
newstairs/back pull request #21
Opened 2024-05-10 10:04 UTC by gyu0918

테스트파일 삭제 
kakao restKey  yml에 추가

2024-05-10 10:29 UTC, ExpeditionMoon reviewed
key 값의 암호화가 잘 되어있는거 같아요!

2024-05-10 21:37 UTC, junodevv requested changes
고생하셨습니다! 암호화 적용 잘하신거같습니다! 
다만 암호화키가 노출된것에 대해서는 수정이 필요할거 같습니다! 그 부분에 댓글 남겨놓았고 
dto부분에도 참고하실 만한 내용이있어 댓글 남겨놓았습니다~!

2024-05-10 21:37 UTC, junodevv commented on src/main/java/project/back/dto/MartLocationDto.java
`@RequiredArgsConstructor`는  final 필드들만으로 생성자로 만드는것인데 final 필드들이 없기도하고 
`@Data`에 `@RequiredArgsConstructor`가 포함되어있기도하고
적절한 생성자를 만들어 놓기도 하셔서 `@RequiredArgsConstructor` 제외하셔도될거같습니다!
@gyu0918

2024-05-11 05:55 UTC, gyu0918 commented on src/main/resources/application.yml
> +    password : 5678
이부분을 저도  고려  했는데  좋은 조언입니다.  개인적으로 환경변수를 설정해야해서 우선적으로 비밀번호까지는  암호화 시키지는 않았는데 프로젝트가  Public으로 되어있으니 고쳐야할거 같네요 자꾸 private 로 생각해서 ... 고맙습니다

2024-05-11 06:13 UTC, gyu0918 commented on src/main/java/project/back/dto/MartLocationDto.java
@Data  말고  @Getter 만  써줘도 될거 같습니다 감사합니다 @junodevv

2024-05-11 06:13 UTC, closed without merging